CREATE TABLE users (
    id NUMBER PRIMARY KEY,
    email VARCHAR2(100) NOT NULL UNIQUE,
    password VARCHAR2(100) NOT NULL,
    name VARCHAR2(50) NOT NULL,
    created_date TIMESTAMP DEFAULT SYSTIMESTAMP,
    modified_date TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE SEQUENCE users_seq
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE; 